base_url = "https://harsh-ps-2003.github.io"
title = "HARSH PRATAP SINGH"
description = "Engineer focused on Distributed Systems, Machine Learning, Databases and Cryptography."
default_language = "en"

# Build settings
compile_sass = true
build_search_index = true
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
smart_punctuation = true
insert_anchor_links = "heading"

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"

[search]
include_title = true
include_description = true
include_path = false
include_content = false
index_format = "elasticlunr_javascript"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[[taxonomies]]
name = "tags"
feed = false

[extra]
author = "Harsh Pratap Singh"

main_menu = [
    { name = "home", url = "/" },
    { name = "writes", url = "/writes/" },
    { name = "reads", url = "/reads/" },
    { name = "resume", url = "/resume/" },
]
